// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AppIntegradorUITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Ingresa al sistema con un usuario y contraseña de administrador.
        /// </summary>
        public void IngresoAlSistemaAdministrador()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchusinEdit = this.UILocalhost44334BingInWindow.UIAddressBarClient.UIAddressandsearchusinEdit;
            HtmlEdit uIUsernameEdit = this.UILocalhost44334BingInWindow.UISistemadeMejoramientDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UILocalhost44334BingInWindow.UISistemadeMejoramientDocument.UIPasswordEdit;
            HtmlButton uIIngresarButton = this.UILocalhost44334BingInWindow.UISistemadeMejoramientDocument.UIIngresarButton;
            #endregion

            // Type 'https://localhost:44334/' in 'Address and search using Bing' text box
            uIAddressandsearchusinEdit.Text = this.IngresoAlSistemaAdministradorParams.UIAddressandsearchusinEditText;

            // Type '{Enter}' in 'Address and search using Bing' text box
            Keyboard.SendKeys(uIAddressandsearchusinEdit, this.IngresoAlSistemaAdministradorParams.UIAddressandsearchusinEditSendKeys, ModifierKeys.None);

            // Type 'admin@mail.com' in 'Username' text box
            uIUsernameEdit.Text = this.IngresoAlSistemaAdministradorParams.UIUsernameEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.IngresoAlSistemaAdministradorParams.UIPasswordEditPassword;

            // Click 'Ingresar' button
            Mouse.Click(uIIngresarButton, new Point(42, 21));
        }
        
        /// <summary>
        /// Abre la interfaz de creación de formularios.
        /// </summary>
        public void AbrirCrearFormulario()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchusinEdit = this.UILocalhost44334BingInWindow.UIAddressBarClient.UIAddressandsearchusinEdit;
            #endregion

            // Type 'https://localhost:44334/Formularios/Create' in 'Address and search using Bing' text box
            uIAddressandsearchusinEdit.Text = this.AbrirCrearFormularioParams.UIAddressandsearchusinEditText;

            // Type '{Enter}' in 'Address and search using Bing' text box
            Keyboard.SendKeys(uIAddressandsearchusinEdit, this.AbrirCrearFormularioParams.UIAddressandsearchusinEditSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// Se prueba los componentes principales de la interfaz de creación de formulario
        /// </summary>
        public void PruebaInterfazBaseDeCrearFormulario()
        {
            #region Variable Declarations
            HtmlEdit uICódigorequeridoEdit = this.UILocalhost44334BingInWindow.UISistemadeMejoramientDocument1.UICódigorequeridoEdit;
            HtmlInputButton uIAgregarseccionesButton = this.UILocalhost44334BingInWindow.UISistemadeMejoramientDocument1.UIAgregarseccionesButton;
            HtmlDiv uIAúnnohaagregadosecciPane1 = this.UILocalhost44334BingInWindow.UISistemadeMejoramientDocument1.UIAúnnohaagregadosecciPane.UIAúnnohaagregadosecciPane1;
            HtmlDiv uICambiossinguardarPane = this.UILocalhost44334BingInWindow.UISistemadeMejoramientDocument1.UICambiossinguardarPane;
            HtmlHyperlink uIVolveralbancodeformuHyperlink = this.UILocalhost44334BingInWindow.UISistemadeMejoramientDocument1.UIVolveralbancodeformuHyperlink;
            #endregion

            // Verify that the 'Id' property of 'Código requerido' text box equals 'textCode'
            Assert.AreEqual(this.PruebaInterfazBaseDeCrearFormularioExpectedValues.UICódigorequeridoEditId, uICódigorequeridoEdit.Id, "No se solicita el código del formulario");

            // Verify that the 'Id' property of 'Agregar secciones' button equals 'AgregarSeccion'
            Assert.AreEqual(this.PruebaInterfazBaseDeCrearFormularioExpectedValues.UIAgregarseccionesButtonId, uIAgregarseccionesButton.Id, "No aparece el botón de Agregar Secciones");

            // Verify that the 'InnerText' property of 'Aún no ha agregado secciones' pane equals 'Aún no ha agregado secciones'
            Assert.AreEqual(this.PruebaInterfazBaseDeCrearFormularioExpectedValues.UIAúnnohaagregadosecciPane1InnerText, uIAúnnohaagregadosecciPane1.InnerText, "No se notifica que no se han agregado secciones");

            // Verify that the 'InnerText' property of 'Cambios sin guardar' pane equals 'Cambios sin guardar '
            Assert.AreEqual(this.PruebaInterfazBaseDeCrearFormularioExpectedValues.UICambiossinguardarPaneInnerText, uICambiossinguardarPane.InnerText, "No se indica que hay cambios sin guardar antes de ingresar el código y el nombre " +
                    "del formulario.");

            // Verify that the 'InnerText' property of 'Volver al banco de formularios' link equals 'Volver al banco de formularios'
            Assert.AreEqual(this.PruebaInterfazBaseDeCrearFormularioExpectedValues.UIVolveralbancodeformuHyperlinkInnerText, uIVolveralbancodeformuHyperlink.InnerText, "No se muestra el botón de volver al banco de formularios");
        }
        
        #region Properties
        public virtual IngresoAlSistemaAdministradorParams IngresoAlSistemaAdministradorParams
        {
            get
            {
                if ((this.mIngresoAlSistemaAdministradorParams == null))
                {
                    this.mIngresoAlSistemaAdministradorParams = new IngresoAlSistemaAdministradorParams();
                }
                return this.mIngresoAlSistemaAdministradorParams;
            }
        }
        
        public virtual AbrirCrearFormularioParams AbrirCrearFormularioParams
        {
            get
            {
                if ((this.mAbrirCrearFormularioParams == null))
                {
                    this.mAbrirCrearFormularioParams = new AbrirCrearFormularioParams();
                }
                return this.mAbrirCrearFormularioParams;
            }
        }
        
        public virtual PruebaInterfazBaseDeCrearFormularioExpectedValues PruebaInterfazBaseDeCrearFormularioExpectedValues
        {
            get
            {
                if ((this.mPruebaInterfazBaseDeCrearFormularioExpectedValues == null))
                {
                    this.mPruebaInterfazBaseDeCrearFormularioExpectedValues = new PruebaInterfazBaseDeCrearFormularioExpectedValues();
                }
                return this.mPruebaInterfazBaseDeCrearFormularioExpectedValues;
            }
        }
        
        public UILocalhost44334BingInWindow UILocalhost44334BingInWindow
        {
            get
            {
                if ((this.mUILocalhost44334BingInWindow == null))
                {
                    this.mUILocalhost44334BingInWindow = new UILocalhost44334BingInWindow();
                }
                return this.mUILocalhost44334BingInWindow;
            }
        }
        #endregion
        
        #region Fields
        private IngresoAlSistemaAdministradorParams mIngresoAlSistemaAdministradorParams;
        
        private AbrirCrearFormularioParams mAbrirCrearFormularioParams;
        
        private PruebaInterfazBaseDeCrearFormularioExpectedValues mPruebaInterfazBaseDeCrearFormularioExpectedValues;
        
        private UILocalhost44334BingInWindow mUILocalhost44334BingInWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'IngresoAlSistemaAdministrador'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class IngresoAlSistemaAdministradorParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'https://localhost:44334/' in 'Address and search using Bing' text box
        /// </summary>
        public string UIAddressandsearchusinEditText = "https://localhost:44334/";
        
        /// <summary>
        /// Type '{Enter}' in 'Address and search using Bing' text box
        /// </summary>
        public string UIAddressandsearchusinEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Type 'admin@mail.com' in 'Username' text box
        /// </summary>
        public string UIUsernameEditText = "admin@mail.com";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "EzVxZkK6ybn67+sVMXn8e+BwIHtiQk3uUFGhNT5ETL8=";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AbrirCrearFormulario'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AbrirCrearFormularioParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'https://localhost:44334/Formularios/Create' in 'Address and search using Bing' text box
        /// </summary>
        public string UIAddressandsearchusinEditText = "https://localhost:44334/Formularios/Create";
        
        /// <summary>
        /// Type '{Enter}' in 'Address and search using Bing' text box
        /// </summary>
        public string UIAddressandsearchusinEditSendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PruebaInterfazBaseDeCrearFormulario'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class PruebaInterfazBaseDeCrearFormularioExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Id' property of 'Código requerido' text box equals 'textCode'
        /// </summary>
        public string UICódigorequeridoEditId = "textCode";
        
        /// <summary>
        /// Verify that the 'Id' property of 'Agregar secciones' button equals 'AgregarSeccion'
        /// </summary>
        public string UIAgregarseccionesButtonId = "AgregarSeccion";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Aún no ha agregado secciones' pane equals 'Aún no ha agregado secciones'
        /// </summary>
        public string UIAúnnohaagregadosecciPane1InnerText = "Aún no ha agregado secciones";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Cambios sin guardar' pane equals 'Cambios sin guardar '
        /// </summary>
        public string UICambiossinguardarPaneInnerText = "Cambios sin guardar ";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Volver al banco de formularios' link equals 'Volver al banco de formularios'
        /// </summary>
        public string UIVolveralbancodeformuHyperlinkInnerText = "Volver al banco de formularios";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UILocalhost44334BingInWindow : BrowserWindow
    {
        
        public UILocalhost44334BingInWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "localhost:44334/ - Bing - Internet Explorer";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("localhost:44334/ - Bing - Internet Explorer");
            this.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UISistemadeMejoramientDocument UISistemadeMejoramientDocument
        {
            get
            {
                if ((this.mUISistemadeMejoramientDocument == null))
                {
                    this.mUISistemadeMejoramientDocument = new UISistemadeMejoramientDocument(this);
                }
                return this.mUISistemadeMejoramientDocument;
            }
        }
        
        public UISistemadeMejoramientDocument1 UISistemadeMejoramientDocument1
        {
            get
            {
                if ((this.mUISistemadeMejoramientDocument1 == null))
                {
                    this.mUISistemadeMejoramientDocument1 = new UISistemadeMejoramientDocument1(this);
                }
                return this.mUISistemadeMejoramientDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressBarClient mUIAddressBarClient;
        
        private UISistemadeMejoramientDocument mUISistemadeMejoramientDocument;
        
        private UISistemadeMejoramientDocument1 mUISistemadeMejoramientDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("localhost:44334/ - Bing - Internet Explorer");
            this.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("localhost:44334/ - Bing - Internet Explorer");
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UISistemadeMejoramientDocument : HtmlDocument
    {
        
        public UISistemadeMejoramientDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "greybg";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Sistema de Mejoramiento Docente";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://localhost:44334/";
            this.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "username-input";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Username";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Username\" class=\"form-control\" id=";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIUsernameEdit.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "password-field";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIPasswordEdit.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlButton UIIngresarButton
        {
            get
            {
                if ((this.mUIIngresarButton == null))
                {
                    this.mUIIngresarButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Ingresar";
                    this.mUIIngresarButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn-blancoUCR";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn-blancoUCR\" type=\"submit\"";
                    this.mUIIngresarButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIIngresarButton.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
                    #endregion
                }
                return this.mUIIngresarButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlButton mUIIngresarButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UISistemadeMejoramientDocument1 : HtmlDocument
    {
        
        public UISistemadeMejoramientDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Sistema de Mejoramiento Docente";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Formularios/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://localhost:44334/Formularios/Create";
            this.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UICódigorequeridoEdit
        {
            get
            {
                if ((this.mUICódigorequeridoEdit == null))
                {
                    this.mUICódigorequeridoEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICódigorequeridoEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "textCode";
                    this.mUICódigorequeridoEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Formulario.Codigo";
                    this.mUICódigorequeridoEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICódigorequeridoEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICódigorequeridoEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "Código requerido";
                    this.mUICódigorequeridoEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "validar-agregar-secciones form-control text-box single-line";
                    this.mUICódigorequeridoEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Formulario.Codigo\" title=\"Código r";
                    this.mUICódigorequeridoEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUICódigorequeridoEdit.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
                    #endregion
                }
                return this.mUICódigorequeridoEdit;
            }
        }
        
        public HtmlInputButton UIAgregarseccionesButton
        {
            get
            {
                if ((this.mUIAgregarseccionesButton == null))
                {
                    this.mUIAgregarseccionesButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIAgregarseccionesButton.SearchProperties[HtmlButton.PropertyNames.Id] = "AgregarSeccion";
                    this.mUIAgregarseccionesButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAgregarseccionesButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Agregar secciones";
                    this.mUIAgregarseccionesButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUIAgregarseccionesButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAgregarseccionesButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn-azulUCR float-right";
                    this.mUIAgregarseccionesButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn-azulUCR float-right\" id=\"Agre";
                    this.mUIAgregarseccionesButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUIAgregarseccionesButton.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
                    #endregion
                }
                return this.mUIAgregarseccionesButton;
            }
        }
        
        public UIAúnnohaagregadosecciPane UIAúnnohaagregadosecciPane
        {
            get
            {
                if ((this.mUIAúnnohaagregadosecciPane == null))
                {
                    this.mUIAúnnohaagregadosecciPane = new UIAúnnohaagregadosecciPane(this);
                }
                return this.mUIAúnnohaagregadosecciPane;
            }
        }
        
        public HtmlDiv UICambiossinguardarPane
        {
            get
            {
                if ((this.mUICambiossinguardarPane == null))
                {
                    this.mUICambiossinguardarPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUICambiossinguardarPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "cambiosGuardados";
                    this.mUICambiossinguardarPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUICambiossinguardarPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Cambios sin guardar ";
                    this.mUICambiossinguardarPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUICambiossinguardarPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUICambiossinguardarPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"cambiosGuardados\"";
                    this.mUICambiossinguardarPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "57";
                    this.mUICambiossinguardarPane.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
                    #endregion
                }
                return this.mUICambiossinguardarPane;
            }
        }
        
        public HtmlHyperlink UIVolveralbancodeformuHyperlink
        {
            get
            {
                if ((this.mUIVolveralbancodeformuHyperlink == null))
                {
                    this.mUIVolveralbancodeformuHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIVolveralbancodeformuHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIVolveralbancodeformuHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIVolveralbancodeformuHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIVolveralbancodeformuHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Volver al banco de formularios";
                    this.mUIVolveralbancodeformuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Formularios/Index";
                    this.mUIVolveralbancodeformuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIVolveralbancodeformuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://localhost:44334/Formularios/Index";
                    this.mUIVolveralbancodeformuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn-blancoUCR";
                    this.mUIVolveralbancodeformuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn-blancoUCR\" href=\"/Formularios";
                    this.mUIVolveralbancodeformuHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "31";
                    this.mUIVolveralbancodeformuHyperlink.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
                    #endregion
                }
                return this.mUIVolveralbancodeformuHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUICódigorequeridoEdit;
        
        private HtmlInputButton mUIAgregarseccionesButton;
        
        private UIAúnnohaagregadosecciPane mUIAúnnohaagregadosecciPane;
        
        private HtmlDiv mUICambiossinguardarPane;
        
        private HtmlHyperlink mUIVolveralbancodeformuHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIAúnnohaagregadosecciPane : HtmlDiv
    {
        
        public UIAúnnohaagregadosecciPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "seccionesActuales";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Aún no ha agregado secciones";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "form-group col-md-12";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"form-group col-md-12\" id=\"seccionesActuales\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "26";
            this.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIAúnnohaagregadosecciPane1
        {
            get
            {
                if ((this.mUIAúnnohaagregadosecciPane1 == null))
                {
                    this.mUIAúnnohaagregadosecciPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAúnnohaagregadosecciPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAúnnohaagregadosecciPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAúnnohaagregadosecciPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Aún no ha agregado secciones";
                    this.mUIAúnnohaagregadosecciPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAúnnohaagregadosecciPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIAúnnohaagregadosecciPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"text-align: center; font-size: large;\"";
                    this.mUIAúnnohaagregadosecciPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "27";
                    this.mUIAúnnohaagregadosecciPane1.WindowTitles.Add("Sistema de Mejoramiento Docente - Internet Explorer");
                    #endregion
                }
                return this.mUIAúnnohaagregadosecciPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIAúnnohaagregadosecciPane1;
        #endregion
    }
}
