CREATE TABLE [dbo].[UsuarioActual]
(
	CorreoUsuario VARCHAR(50) NOT NULL PRIMARY KEY,
	Perfil VARCHAR(50) NOT NULL,
	CodCarrera VARCHAR(10) NOT NULL,
	CodEnfasis VARCHAR(10) NOT NULL
	FOREIGN KEY (CorreoUsuario) REFERENCES Persona (Correo) ON UPDATE CASCADE ON DELETE CASCADE
	FOREIGN KEY (Perfil) REFERENCES Perfil (Nombre) ON UPDATE CASCADE ON DELETE CASCADE
	FOREIGN KEY (CodCarrera, CodEnfasis) REFERENCES Enfasis (CodCarrera, Codigo) ON UPDATE CASCADE ON DELETE CASCADE
)
