CREATE TABLE Pregunta_con_respuesta_libre
(
	Codigo VARCHAR(8) NOT NULL PRIMARY KEY,
	CONSTRAINT fkResLibreCodigo FOREIGN KEY(Codigo) REFERENCES Pregunta(Codigo) ON DELETE CASCADE ON UPDATE CASCADE,
)
