//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accionable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accionable()
        {
            this.Funcionario = new HashSet<Funcionario>();
        }
    
        public int codPlan { get; set; }
        public string nombreObj { get; set; }
        public string descripAcMej { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string tipo { get; set; }
        public Nullable<int> peso { get; set; }
        public Nullable<int> pesoPorcentaje { get; set; }
    
        public virtual AccionDeMejora AccionDeMejora { get; set; }
        public virtual AccionableEscala AccionableEscala { get; set; }
        public virtual AccionablePorcentaje AccionablePorcentaje { get; set; }
        public virtual AccionableSiNo AccionableSiNo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
}
