//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccionableSiNo
    {
        public int codPlan { get; set; }
        public string nombreObj { get; set; }
        public string descripAcMej { get; set; }
        public string descripcion { get; set; }
        public string avance { get; set; }
    
        public virtual Accionable Accionable { get; set; }
    }
}
