//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compuesto_Por
    {
        public int Codigo_Plan { get; set; }
        public Nullable<int> Codigo_Obj { get; set; }
    
        public virtual Objetivo Objetivo { get; set; }
    }
}
