//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnlaceSeguro
    {
        public string Hash { get; set; }
        public string UsuarioAsociado { get; set; }
        public string UrlReal { get; set; }
        public Nullable<System.DateTime> Expira { get; set; }
        public int Usos { get; set; }
        public bool ReestablecerContrasenna { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
