//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnlaceSeguro
    {
        public string Hash { get; set; }
        public string UsuarioAsociado { get; set; }
        public string UrlReal { get; set; }
        public Nullable<System.DateTime> Expira { get; set; }
        public int Usos { get; set; }
        public bool ReestablecerContrasenna { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
