
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppIntegrador.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Formulario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Formulario()
    {

        this.Activa_por = new HashSet<Activa_por>();

        this.Formulario_tiene_seccion = new HashSet<Formulario_tiene_seccion>();

        this.Respuestas_a_formulario = new HashSet<Respuestas_a_formulario>();

        this.PlanDeMejora = new HashSet<PlanDeMejora>();

    }

    [Required(ErrorMessage = "Campo requerido")]
    public string Codigo { get; set; }
    
    [Required(ErrorMessage = "Campo requerido")]
    public string Nombre { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Activa_por> Activa_por { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Formulario_tiene_seccion> Formulario_tiene_seccion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Respuestas_a_formulario> Respuestas_a_formulario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PlanDeMejora> PlanDeMejora { get; set; }

}

}
