//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opciones_de_seleccion
    {
        public string Codigo { get; set; }
        public int Orden { get; set; }
        public string Texto { get; set; }
    
        public virtual Pregunta_con_opciones_de_seleccion Pregunta_con_opciones_de_seleccion { get; set; }
    }
}
