//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opciones_seleccionadas_respuesta_con_opciones
    {
        public string FCodigo { get; set; }
        public string Correo { get; set; }
        public string CSigla { get; set; }
        public byte GNumero { get; set; }
        public int GAnno { get; set; }
        public byte GSemestre { get; set; }
        public System.DateTime Fecha { get; set; }
        public string PCodigo { get; set; }
        public string SCodigo { get; set; }
        public byte OpcionSeleccionada { get; set; }
    
        public virtual Responde_respuesta_con_opciones Responde_respuesta_con_opciones { get; set; }
    }
}
