//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opciones_seleccionadas_respuesta_con_opciones
    {
        public string FCodigo { get; set; }
        public string Correo { get; set; }
        public string CSigla { get; set; }
        public byte GNumero { get; set; }
        public int GAnno { get; set; }
        public byte GSemestre { get; set; }
        public System.DateTime Fecha { get; set; }
        public string PCodigo { get; set; }
        public string SCodigo { get; set; }
        public byte OpcionSeleccionada { get; set; }
    
        public virtual Responde_respuesta_con_opciones Responde_respuesta_con_opciones { get; set; }
    }
}
