//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilPermiso
    {
        public string Perfil { get; set; }
        public int PermisoId { get; set; }
        public string CodCarrera { get; set; }
        public string CodEnfasis { get; set; }
    
        public virtual Enfasis Enfasis { get; set; }
        public virtual Perfil Perfil1 { get; set; }
        public virtual Permiso Permiso { get; set; }
    }
}
