//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public string Correo { get; set; }
        public string CorreoAlt { get; set; }
        public string Identificacion { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Usuario { get; set; }
        public string TipoIdentificacion { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
