//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PlanDeMejora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanDeMejora()
        {
            this.Objetivo = new HashSet<Objetivo>();
        }
    
        [Display(Name = "Cédula del profesor")]
        [MaxLength(10)]
        public string CedProf { get; set; }
        [Display(Name = "Código del plan")]
        public int Codigo { get; set; }
        [Display(Name = "Nombre")]
        [DataType(DataType.Text)]
        public string Nombre { get; set; }
        [Display(Name = "Inicio")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FechaInicio { get; set; }
        [Display(Name = "Finalización")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FechaFin { get; set; }
        [Display(Name = "Código")]
        public string CodigoF { get; set; }
        [Display(Name = "Cédula Profesor")]
        public string CedProfAsig { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Objetivo> Objetivo { get; set; }
        [Display(Name = "Cédula Profesor")]
        public virtual Profesor Profesor { get; set; }
        [Display(Name = "Cédula Profesor1")]
        public virtual Profesor Profesor1 { get; set; }
    }
}
