//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        public string Codigo { get; set; }
        public string Enunciado { get; set; }
    
        public virtual Pregunta_con_opciones Pregunta_con_opciones { get; set; }
    }
}
