//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta_con_opciones
    {
        public string Codigo { get; set; }
        public string TituloCampoObservacion { get; set; }
    
        public virtual Escalar Escalar { get; set; }
        public virtual Pregunta Pregunta { get; set; }
        public virtual Pregunta_con_opciones_de_seleccion Pregunta_con_opciones_de_seleccion { get; set; }
        public virtual Si_no_nr Si_no_nr { get; set; }
    }
}
