//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas_a_formulario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respuestas_a_formulario()
        {
            this.Responde_respuesta_con_opciones = new HashSet<Responde_respuesta_con_opciones>();
            this.Responde_respuesta_libre = new HashSet<Responde_respuesta_libre>();
            this.PlanDeMejora = new HashSet<PlanDeMejora>();
        }
    
        public string FCodigo { get; set; }
        public string Correo { get; set; }
        public string CSigla { get; set; }
        public byte GNumero { get; set; }
        public int GAnno { get; set; }
        public byte GSemestre { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Formulario Formulario { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responde_respuesta_con_opciones> Responde_respuesta_con_opciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responde_respuesta_libre> Responde_respuesta_libre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanDeMejora> PlanDeMejora { get; set; }
    }
}
