//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccion_tiene_pregunta
    {
        public string SCodigo { get; set; }
        public string PCodigo { get; set; }
        public int Orden { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
