//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccion_tiene_pregunta
    {
        public string SCodigo { get; set; }
        public string PCodigo { get; set; }
        public int Orden { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
