//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visualizacion_Respuestas_Escalar
    {
        public string Codigo { get; set; }
        public int Incremento { get; set; }
        public int Minimo { get; set; }
        public int Maximo { get; set; }
        public string FCodigo { get; set; }
        public string Username { get; set; }
        public string CSigla { get; set; }
        public int GNumero { get; set; }
        public int GAnno { get; set; }
        public int GSemestre { get; set; }
        public System.DateTime Fecha { get; set; }
        public string PCodigo { get; set; }
        public int OpcionSeleccionada { get; set; }
    }
}
